/** Opciones de giro del negocio para Configuración y Onboarding */
export const GIRO_OPTIONS = [
  'Distribución de alimentos y bebidas',
  'Distribución de productos de limpieza',
  'Distribución de materiales de construcción',
  'Distribución de productos farmacéuticos',
  'Distribución de productos agrícolas',
  'Distribución de productos químicos',
  'Distribución de autopartes',
  'Distribución de papelería y oficina',
  'Distribución de tecnología y cómputo',
  'Distribución de ferretería',
  'Distribución de productos eléctricos',
  'Distribución de productos industriales',
  'Distribución de productos veterinarios',
  'Distribución de cosméticos y cuidado personal',
  'Distribución de textiles y ropa',
  'Distribución de muebles y hogar',
  'Distribución de plásticos y desechables',
  'Distribución de pinturas y recubrimientos',
  'Distribución de lubricantes y aceites',
  'Distribución de gas y combustibles',
  'Mayorista / Abarrotes',
  'Mayorista / Licores y vinos',
  'Mayorista / Dulces y botanas',
  'Mayorista / Lácteos y refrigerados',
  'Comercializadora general',
  'Fabricante con venta directa',
  'Importadora / Exportadora',
  'Venta por catálogo',
  'E-commerce / Venta en línea',
  'Servicios profesionales',
  'Servicios de mantenimiento',
  'Servicios de logística',
  'Restaurante / Food service',
  'Retail / Tienda minorista',
  'Agencia de publicidad / Marketing',
  'Construcción y obra civil',
  'Inmobiliaria',
  'Transporte y mudanzas',
  'Salud y equipamiento médico',
  'Educación y capacitación',
  'Otro',
] as const

export type GiroOption = (typeof GIRO_OPTIONS)[number]
