/** Opciones de giro del negocio para Configuración y Onboarding */
export const GIRO_OPTIONS = [
  'Alimentos y bebidas',
  'Productos de limpieza y hogar',
  'Cosméticos y cuidado personal',
  'Dulces, botanas y confitería',
  'Lácteos y refrigerados',
  'Licores, vinos y bebidas alcohólicas',
  'Productos farmacéuticos',
  'Productos veterinarios',
  'Salud y equipamiento médico',
  'Materiales de construcción',
  'Ferretería y herramientas',
  'Productos eléctricos e iluminación',
  'Pinturas y recubrimientos',
  'Plásticos y desechables',
  'Productos industriales',
  'Tecnología y cómputo',
  'Papelería y artículos de oficina',
  'Muebles y mobiliario',
  'Autopartes y accesorios',
  'Lubricantes, aceites y combustibles',
  'Transporte y logística',
  'Productos agrícolas y agropecuarios',
  'Productos químicos',
  'Textiles, ropa y calzado',
  'Tienda minorista / Retail',
  'Abarrotes y mayoreo',
  'E-commerce / Venta en línea',
  'Venta por catálogo',
  'Comercializadora general',
  'Importadora / Exportadora',
  'Fabricante con venta directa',
  'Servicios profesionales',
  'Servicios de mantenimiento',
  'Restaurante / Food service',
  'Agencia de publicidad / Marketing',
  'Construcción y obra civil',
  'Inmobiliaria',
  'Educación y capacitación',
  'Otro',
] as const

export type GiroOption = (typeof GIRO_OPTIONS)[number]
